## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# working directory (required):
workdir: "/home/DSUmranYaman/DervisSalih/output_annseq"

# prefix of all output files (optional; default = "sample")
sample_name: "sample1"

# reference genome (required)
genome: "/home/DSUmranYaman/DervisSalih/references/mouse/mm10/GRCm38.p6.genome.fa"

# ONS reads in fastq format
reads_fastq: "/home/DSUmranYaman/DervisSalih/pool1/barcode01"

# The path above is a directory, find and concatenate fastq files:
concatenate: true

# threads (default = 30)
threads: 50

# input annotation data required for sqanti (required)
# make sure the contig names in the annotation matches the input SAM file
gtf: "/home/DSUmranYaman/DervisSalih/references/mouse/mm10/gencode.vM21.annotation.gtf"


